[theme]
primaryColor = "#00A67E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
